force-app/main/default/objects/Content__c/Content__c.object-meta.xml
<CustomObject>
    <label>Content</label>
    <nameField>
        <label>Content Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Content__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Animation</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Sci-Fi</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Documentary</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Musical</fullName>
            </value>
            <value>
                <fullName>Suspense</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Content__c/fields/Content_type__c.field-meta.xml
<CustomField>
    <fullName>Content_type__c</fullName>
    <label>Content type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Movie</fullName>
            </value>
            <value>
                <fullName>Serie</fullName>
            </value>
            <value>
                <fullName>Documentary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Content__c/fields/Movie_poster_url__c.field-meta.xml
<CustomField>
    <fullName>Movie_poster_url__c</fullName>
    <label>Movie poster url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Content__c/recordTypes/Movie.recordType-meta.xml
<RecordType>
    <fullName>Movie</fullName>
    <active>true</active>
    <label>Movie</label>
</RecordType>

force-app/main/default/objects/Content__c/recordTypes/Serie.recordType-meta.xml
<RecordType>
    <fullName>Serie</fullName>
    <active>true</active>
    <label>Serie</label>
</RecordType>

force-app/main/default/classes/ContentSelector.cls
public with sharing class ContentSelector {
    
    @AuraEnabled(cacheable=true)
    public static Content__c getContentById(Id contentId) {
        if (contentId == null) return null;

        return [
            SELECT Name, Movie_poster_url__c, Content_type__c, Category__c
            FROM Content__c
            WHERE Id = :contentId
            LIMIT 1
        ];
    }
    
    public static List<Content__c> getSeries(){
        return  [
                SELECT Name, Movie_poster_url__c, Content_type__c, Category__c
                FROM Content__c
                WHERE Content_type__c = 'Serie'
            ];
    }
    
    public static List<Content__c> getMovies(){
        return  [
                SELECT Name, Movie_poster_url__c, Content_type__c, Category__c
                FROM Content__c
                WHERE Content_type__c = 'Movie'
            ];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Content__c> getContentByClient(Id accId){
        if (accId == null) return null;
        List<Content__c> results = NEW List<Content__c>();
        Account acc = [Select Subscription_type__c From Account where Id = :accId LIMIT 1];
        String contentType = acc.Subscription_type__c;
        if(contentType == 'Total'){
            results.addall(getSeries());
            results.addall(getMovies());
        } else if(contentType == 'Serie'){
            results.addall(getSeries());
        } else if(contentType == 'Movies and documentaries'){
            results.addall(getMovies());
    	}
        return results;
	}
}